### ISSUE TITLE
Fails to build with 5.0

### ISSUE THREAD

**Issue by ciniglio** [janestreet/sexplib0#10]
```
#=== ERROR while compiling sexplib0.v0.16~preview.126.09+332 ==================#
# context     2.1.2 | macos/x86_64 | ocaml-base-compiler.5.0.0~alpha0 | https://ocaml.janestreet.com/opam-repository
# path        ~/.opam/5.0.0~alpha0/.opam-switch/build/sexplib0.v0.16~preview.126.09+332
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p sexplib0 -j 15
# exit-code   1
# env-file    ~/.opam/log/sexplib0-61071-6cff5c.env
# output-file ~/.opam/log/sexplib0-61071-6cff5c.out
### output ###
# (cd _build/default && /Users/alejandro/.opam/5.0.0~alpha0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.sexplib0.objs/byte -intf-suffix .ml -no-alias-deps -open Sexplib0__ -o src/.sexplib0.objs/byte/sexplib0__Sexp_conv.cmo -c -impl src/sexp_conv.ml)
# File "src/sexp_conv.ml", line 99, characters 15-31:
# 99 |       let id = Obj.extension_id
#                     ^^^^^^^^^^^^^^^^
# Error: Unbound value Obj.extension_id
# (cd _build/default && /Users/alejandro/.opam/5.0.0~alpha0/bin/ocamlopt.opt -w -40 -g -I src/.sexplib0.objs/byte -I src/.sexplib0.objs/native -intf-suffix .ml -no-alias-deps -open Sexplib0__ -o src/.sexplib0.objs/native/sexplib0__Sexp_conv.cmx -c -impl src/sexp_conv.ml)
# File "src/sexp_conv.ml", line 99, characters 15-31:
# 99 |       let id = Obj.extension_id
#                     ^^^^^^^^^^^^^^^^
# Error: Unbound value Obj.extension_id
```

**Comment by smuenzel** [comment]
The lastest version has a different problem with 5.0
```
[ERROR] The compilation of sexplib0.v0.16~preview.127.22+307 failed at "dune build -p sexplib0 -j 15".

#=== ERROR while compiling sexplib0.v0.16~preview.127.22+307 ==================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.5.0.0~alpha0 | git+ssh://git@github.com/janestreet/opam-repository.git
# path        ~/.opam/5.0.0~alpha0/.opam-switch/build/sexplib0.v0.16~preview.127.22+307
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p sexplib0 -j 15
# exit-code   1
# env-file    ~/.opam/log/sexplib0-914036-95c7b3.env
# output-file ~/.opam/log/sexplib0-914036-95c7b3.out
### output ###
# (cd _build/default && /home/stefan/.opam/5.0.0~alpha0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.sexplib0.objs/byte -intf-suffix .ml -no-alias-deps -open Sexplib0__ -o src/.sexplib0.objs/byte/sexplib0__Sexp_conv.cmo -c -impl src/sexp_conv.ml)
# File "src/sexp_conv.ml", line 395, characters 32-46:
# 395 |     ; ( [%extension_constructor Stream.Failure]
#                                       ^^^^^^^^^^^^^^
# Error: Unbound module Stream
# (cd _build/default && /home/stefan/.opam/5.0.0~alpha0/bin/ocamlopt.opt -w -40 -g -I src/.sexplib0.objs/byte -I src/.sexplib0.objs/native -intf-suffix .ml -no-alias-deps -open Sexplib0__ -o src/.sexplib0.objs/native/sexplib0__Sexp_conv.cmx -c -impl src/sexp_conv.ml)
# File "src/sexp_conv.ml", line 395, characters 32-46:
# 395 |     ; ( [%extension_constructor Stream.Failure]
#                                       ^^^^^^^^^^^^^^
# Error: Unbound module Stream
```

**Comment by ceastlund** [comment]
Fixed in `v0.16.0`.
